/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import javax.swing.JOptionPane;
import lamborghini.EmpleadosLamborghini;
import maserati.EmpleadosMaserati;

/**
 *
 * @author Valeria
 */
public class InterfazMain extends javax.swing.JFrame {

    /**
     * Creates new form Pestañas
     */
    public InterfazMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CantidadCarrosLamborghini = new javax.swing.JLabel();
        CantidadCarroceriaLamborghini = new javax.swing.JLabel();
        CantidadRuedasLamborghini = new javax.swing.JLabel();
        CantidadMotorLamborghini = new javax.swing.JLabel();
        CantidadAccesoriosLamborghini = new javax.swing.JLabel();
        CantidadChasisLamborghini = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SalariosLamborghini = new javax.swing.JLabel();
        GananciasLamborghini = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EntregaLamborghini = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eCarroceriaLamborghini = new javax.swing.JLabel();
        eMotorLamborghini = new javax.swing.JLabel();
        eRuedasLamborghini = new javax.swing.JLabel();
        eEnsambladorLamborghini = new javax.swing.JLabel();
        eChasisLamborghini = new javax.swing.JLabel();
        eAccesoriosLamborghini = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AumentarChasisLamborghini = new java.awt.Button();
        DisminuirChasisLamborghini = new java.awt.Button();
        AumentarCarroceriaLamborghini = new java.awt.Button();
        DisminuirCarroceriaLamborghini = new java.awt.Button();
        DisminuirAccesoriosLamborghini = new java.awt.Button();
        DisminuirMotorLamborghini = new java.awt.Button();
        DisminuirRuedasLamborghini = new java.awt.Button();
        DisminuirEnsambladorLamborghini = new java.awt.Button();
        AumentarRuedasLamborghini = new java.awt.Button();
        AumentarAccesoriosLamborghini = new java.awt.Button();
        AumentarEnsambladorLamborghini = new java.awt.Button();
        AumentarMotorLamborghini = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CantidadCarrosMaserati = new javax.swing.JLabel();
        CantidadCarroceriaMaserati = new javax.swing.JLabel();
        CantidadRuedasMaserati = new javax.swing.JLabel();
        CantidadMotorMaserati = new javax.swing.JLabel();
        CantidadAccesoriosMaserati = new javax.swing.JLabel();
        CantidadChasisMaserati = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        SalariosMaserati = new javax.swing.JLabel();
        GananciasMaserati = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        EntregaMaserati = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        eCarroceriaMaserati = new javax.swing.JLabel();
        eMotorMaserati = new javax.swing.JLabel();
        eRuedasMaserati = new javax.swing.JLabel();
        eEnsambladorMaserati = new javax.swing.JLabel();
        eChasisMaserati = new javax.swing.JLabel();
        eAccesoriosMaserati = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        AumentarChasisMaserati = new java.awt.Button();
        DisminuirChasisMaserati = new java.awt.Button();
        AumentarCarroceriaMaserati = new java.awt.Button();
        DisminuirCarroceriaMaserati = new java.awt.Button();
        DisminuirAccesoriosMaserati = new java.awt.Button();
        DisminuirMotorMaserati = new java.awt.Button();
        DisminuirRuedasMaserati = new java.awt.Button();
        DisminuirEnsambladorMaserati = new java.awt.Button();
        AumentarRuedasMaserati = new java.awt.Button();
        AumentarAccesoriosMaserati = new java.awt.Button();
        AumentarEnsambladorMaserati = new java.awt.Button();
        AumentarMotorMaserati = new java.awt.Button();
        jTabbedPane5 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chasis");

        jLabel2.setText("Carroceria");

        jLabel3.setText("Motor");

        jLabel4.setText("Ruedas");

        jLabel5.setText("Accesorios");

        CantidadCarrosLamborghini.setText("0");

        CantidadCarroceriaLamborghini.setText("0");

        CantidadRuedasLamborghini.setText("0");

        CantidadMotorLamborghini.setText("0");

        CantidadAccesoriosLamborghini.setText("0");

        CantidadChasisLamborghini.setText("0");

        jLabel6.setText("Salarios");

        jLabel7.setText("Carros");

        jLabel8.setText("Ganancias");

        SalariosLamborghini.setText("0");

        GananciasLamborghini.setText("0");

        jLabel9.setText("Entrega");

        EntregaLamborghini.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Lamborguini");
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 16));

        jLabel11.setText("Trab Asig");

        eCarroceriaLamborghini.setText("1");

        eMotorLamborghini.setText("1");

        eRuedasLamborghini.setText("1");

        eEnsambladorLamborghini.setText("1");

        eChasisLamborghini.setText("1");

        eAccesoriosLamborghini.setText("1");

        jLabel13.setText("Ensamblador");

        AumentarChasisLamborghini.setActionCommand("Contratar");
        AumentarChasisLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarChasisLamborghini.setLabel("A");
        AumentarChasisLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarChasisLamborghiniActionPerformed(evt);
            }
        });

        DisminuirChasisLamborghini.setActionCommand("Contratar");
        DisminuirChasisLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirChasisLamborghini.setLabel("D");
        DisminuirChasisLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirChasisLamborghiniActionPerformed(evt);
            }
        });

        AumentarCarroceriaLamborghini.setActionCommand("Contratar");
        AumentarCarroceriaLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarCarroceriaLamborghini.setLabel("A");
        AumentarCarroceriaLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarCarroceriaLamborghiniActionPerformed(evt);
            }
        });

        DisminuirCarroceriaLamborghini.setActionCommand("Contratar");
        DisminuirCarroceriaLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirCarroceriaLamborghini.setLabel("D");
        DisminuirCarroceriaLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirCarroceriaLamborghiniActionPerformed(evt);
            }
        });

        DisminuirAccesoriosLamborghini.setActionCommand("Contratar");
        DisminuirAccesoriosLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirAccesoriosLamborghini.setLabel("D");
        DisminuirAccesoriosLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirAccesoriosLamborghiniActionPerformed(evt);
            }
        });

        DisminuirMotorLamborghini.setActionCommand("Contratar");
        DisminuirMotorLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirMotorLamborghini.setLabel("D");
        DisminuirMotorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirMotorLamborghiniActionPerformed(evt);
            }
        });

        DisminuirRuedasLamborghini.setActionCommand("Contratar");
        DisminuirRuedasLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirRuedasLamborghini.setLabel("D");
        DisminuirRuedasLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirRuedasLamborghiniActionPerformed(evt);
            }
        });

        DisminuirEnsambladorLamborghini.setActionCommand("Contratar");
        DisminuirEnsambladorLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirEnsambladorLamborghini.setLabel("D");
        DisminuirEnsambladorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirEnsambladorLamborghiniActionPerformed(evt);
            }
        });

        AumentarRuedasLamborghini.setActionCommand("Contratar");
        AumentarRuedasLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarRuedasLamborghini.setLabel("A");
        AumentarRuedasLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarRuedasLamborghiniActionPerformed(evt);
            }
        });

        AumentarAccesoriosLamborghini.setActionCommand("Contratar");
        AumentarAccesoriosLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarAccesoriosLamborghini.setLabel("A");
        AumentarAccesoriosLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarAccesoriosLamborghiniActionPerformed(evt);
            }
        });

        AumentarEnsambladorLamborghini.setActionCommand("Contratar");
        AumentarEnsambladorLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarEnsambladorLamborghini.setLabel("A");
        AumentarEnsambladorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarEnsambladorLamborghiniActionPerformed(evt);
            }
        });

        AumentarMotorLamborghini.setActionCommand("Contratar");
        AumentarMotorLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarMotorLamborghini.setLabel("A");
        AumentarMotorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarMotorLamborghiniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantidadChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(eChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(CantidadCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DisminuirRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DisminuirMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(AumentarMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AumentarEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DisminuirEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(CantidadMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(CantidadRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addGap(68, 68, 68))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(134, 134, 134)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DisminuirAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AumentarAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CantidadCarrosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(GananciasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalariosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntregaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DisminuirChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AumentarChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisminuirCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AumentarCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(SalariosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(GananciasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadCarrosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CantidadChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AumentarChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarRuedasLamborghini, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarAccesoriosLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AumentarCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DisminuirRuedasLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DisminuirChasisLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirCarroceriaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirAccesoriosLamborghini, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirMotorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(eEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DisminuirEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AumentarEnsambladorLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntregaLamborghini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Lamborghini", jPanel1);

        jLabel12.setText("Chasis");

        jLabel14.setText("Carroceria");

        jLabel15.setText("Motor");

        jLabel16.setText("Ruedas");

        jLabel17.setText("Accesorios");

        CantidadCarrosMaserati.setText("0");

        CantidadCarroceriaMaserati.setText("0");

        CantidadRuedasMaserati.setText("0");

        CantidadMotorMaserati.setText("0");

        CantidadAccesoriosMaserati.setText("0");

        CantidadChasisMaserati.setText("0");

        jLabel18.setText("Salarios");

        jLabel19.setText("Carros");

        jLabel20.setText("Ganancias");

        SalariosMaserati.setText("0");

        GananciasMaserati.setText("0");

        jLabel21.setText("Entrega");

        EntregaMaserati.setText("0");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("Maserati");
        jLabel22.setMaximumSize(new java.awt.Dimension(80, 16));

        jLabel23.setText("Trab Asig");

        eCarroceriaMaserati.setText("1");

        eMotorMaserati.setText("1");

        eRuedasMaserati.setText("1");

        eEnsambladorMaserati.setText("1");

        eChasisMaserati.setText("1");

        eAccesoriosMaserati.setText("1");

        jLabel24.setText("Ensamblador");

        AumentarChasisMaserati.setActionCommand("Contratar");
        AumentarChasisMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarChasisMaserati.setLabel("A");
        AumentarChasisMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarChasisMaseratiActionPerformed(evt);
            }
        });

        DisminuirChasisMaserati.setActionCommand("Contratar");
        DisminuirChasisMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirChasisMaserati.setLabel("D");
        DisminuirChasisMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirChasisMaseratiActionPerformed(evt);
            }
        });

        AumentarCarroceriaMaserati.setActionCommand("Contratar");
        AumentarCarroceriaMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarCarroceriaMaserati.setLabel("A");
        AumentarCarroceriaMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarCarroceriaMaseratiActionPerformed(evt);
            }
        });

        DisminuirCarroceriaMaserati.setActionCommand("Contratar");
        DisminuirCarroceriaMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirCarroceriaMaserati.setLabel("D");
        DisminuirCarroceriaMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirCarroceriaMaseratiActionPerformed(evt);
            }
        });

        DisminuirAccesoriosMaserati.setActionCommand("Contratar");
        DisminuirAccesoriosMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirAccesoriosMaserati.setLabel("D");
        DisminuirAccesoriosMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirAccesoriosMaseratiActionPerformed(evt);
            }
        });

        DisminuirMotorMaserati.setActionCommand("Contratar");
        DisminuirMotorMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirMotorMaserati.setLabel("D");
        DisminuirMotorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirMotorMaseratiActionPerformed(evt);
            }
        });

        DisminuirRuedasMaserati.setActionCommand("Contratar");
        DisminuirRuedasMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirRuedasMaserati.setLabel("D");
        DisminuirRuedasMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirRuedasMaseratiActionPerformed(evt);
            }
        });

        DisminuirEnsambladorMaserati.setActionCommand("Contratar");
        DisminuirEnsambladorMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirEnsambladorMaserati.setLabel("D");
        DisminuirEnsambladorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirEnsambladorMaseratiActionPerformed(evt);
            }
        });

        AumentarRuedasMaserati.setActionCommand("Contratar");
        AumentarRuedasMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarRuedasMaserati.setLabel("A");
        AumentarRuedasMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarRuedasMaseratiActionPerformed(evt);
            }
        });

        AumentarAccesoriosMaserati.setActionCommand("Contratar");
        AumentarAccesoriosMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarAccesoriosMaserati.setLabel("A");
        AumentarAccesoriosMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarAccesoriosMaseratiActionPerformed(evt);
            }
        });

        AumentarEnsambladorMaserati.setActionCommand("Contratar");
        AumentarEnsambladorMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarEnsambladorMaserati.setLabel("A");
        AumentarEnsambladorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarEnsambladorMaseratiActionPerformed(evt);
            }
        });

        AumentarMotorMaserati.setActionCommand("Contratar");
        AumentarMotorMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarMotorMaserati.setLabel("A");
        AumentarMotorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarMotorMaseratiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantidadChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(eChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(CantidadCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(eMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(CantidadMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AumentarMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DisminuirRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DisminuirMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(AumentarEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DisminuirEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(CantidadRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel18))
                                    .addGap(68, 68, 68))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(134, 134, 134)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantidadAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DisminuirAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AumentarAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(148, 148, 148)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(CantidadCarrosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(GananciasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalariosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EntregaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DisminuirChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AumentarChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisminuirCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AumentarCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(SalariosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(GananciasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel19)
                        .addGap(23, 23, 23)
                        .addComponent(CantidadCarrosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel23))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantidadMotorMaserati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CantidadChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CantidadCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CantidadRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CantidadAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AumentarChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarRuedasMaserati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AumentarAccesoriosMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AumentarCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AumentarMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DisminuirRuedasMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DisminuirChasisMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirCarroceriaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirAccesoriosMaserati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirMotorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(eEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DisminuirEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AumentarEnsambladorMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntregaMaserati, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Maserati", jPanel2);
        jTabbedPane2.addTab("Lector de Archivos", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AumentarMotorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarMotorMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eMotor= EmpleadosMaserati.eMotor + 1;
            InterfazMain.eMotorMaserati.setText(String.valueOf(EmpleadosMaserati.eMotor));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarMotorMaseratiActionPerformed

    private void AumentarEnsambladorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarEnsambladorMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eEnsamblador= EmpleadosMaserati.eEnsamblador + 1;
            InterfazMain.eEnsambladorMaserati.setText(String.valueOf(EmpleadosMaserati.eEnsamblador));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarEnsambladorMaseratiActionPerformed

    private void AumentarAccesoriosMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarAccesoriosMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eAccesorios= EmpleadosMaserati.eAccesorios + 1;
            InterfazMain.eAccesoriosMaserati.setText(String.valueOf(EmpleadosMaserati.eAccesorios));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarAccesoriosMaseratiActionPerformed

    private void AumentarRuedasMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarRuedasMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eRuedas= EmpleadosMaserati.eRuedas + 1;
            InterfazMain.eRuedasMaserati.setText(String.valueOf(EmpleadosMaserati.eRuedas));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarRuedasMaseratiActionPerformed

    private void DisminuirEnsambladorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirEnsambladorMaseratiActionPerformed
        if(EmpleadosMaserati.eEnsamblador>1){
            EmpleadosMaserati.eEnsamblador= EmpleadosMaserati.eEnsamblador -1;
            InterfazMain.eEnsambladorMaserati.setText(String.valueOf(EmpleadosMaserati.eEnsamblador));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirEnsambladorMaseratiActionPerformed

    private void DisminuirRuedasMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirRuedasMaseratiActionPerformed
        if(EmpleadosMaserati.eRuedas>1){
            EmpleadosMaserati.eRuedas= EmpleadosMaserati.eRuedas -1;
            InterfazMain.eRuedasMaserati.setText(String.valueOf(EmpleadosMaserati.eRuedas));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirRuedasMaseratiActionPerformed

    private void DisminuirMotorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirMotorMaseratiActionPerformed
        if(EmpleadosMaserati.eMotor>1){
            EmpleadosMaserati.eMotor= EmpleadosMaserati.eMotor -1;
            InterfazMain.eMotorMaserati.setText(String.valueOf(EmpleadosMaserati.eMotor));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirMotorMaseratiActionPerformed

    private void DisminuirAccesoriosMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirAccesoriosMaseratiActionPerformed
        if(EmpleadosMaserati.eAccesorios>1){
            EmpleadosMaserati.eAccesorios= EmpleadosMaserati.eAccesorios -1;
            InterfazMain.eAccesoriosMaserati.setText(String.valueOf(EmpleadosMaserati.eAccesorios));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirAccesoriosMaseratiActionPerformed

    private void DisminuirCarroceriaMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirCarroceriaMaseratiActionPerformed
        if(EmpleadosMaserati.eCarroceria>1){
            EmpleadosMaserati.eCarroceria= EmpleadosMaserati.eCarroceria -1;
            InterfazMain.eCarroceriaMaserati.setText(String.valueOf(EmpleadosMaserati.eCarroceria));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirCarroceriaMaseratiActionPerformed

    private void AumentarCarroceriaMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarCarroceriaMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eCarroceria= EmpleadosMaserati.eCarroceria + 1;
            InterfazMain.eCarroceriaMaserati.setText(String.valueOf(EmpleadosMaserati.eCarroceria));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarCarroceriaMaseratiActionPerformed

    private void DisminuirChasisMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirChasisMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis>1){
           EmpleadosMaserati.eChasis= EmpleadosMaserati.eChasis -1;
            InterfazMain.eChasisMaserati.setText(String.valueOf(EmpleadosMaserati.eChasis));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirChasisMaseratiActionPerformed

    private void AumentarChasisMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarChasisMaseratiActionPerformed
        if(EmpleadosMaserati.eChasis+EmpleadosMaserati.eCarroceria+EmpleadosMaserati.eMotor+
            EmpleadosMaserati.eRuedas+EmpleadosMaserati.eAccesorios+EmpleadosMaserati.eEnsamblador < EmpleadosMaserati.Empleados){
            EmpleadosMaserati.eChasis= EmpleadosMaserati.eChasis + 1;
            InterfazMain.eChasisMaserati.setText(String.valueOf(EmpleadosMaserati.eChasis));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarChasisMaseratiActionPerformed

    private void AumentarMotorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarMotorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eMotor= EmpleadosLamborghini.eMotor + 1;
            InterfazMain.eMotorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eMotor));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarMotorLamborghiniActionPerformed

    private void AumentarEnsambladorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarEnsambladorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eEnsamblador= EmpleadosLamborghini.eEnsamblador + 1;
            InterfazMain.eEnsambladorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eEnsamblador));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarEnsambladorLamborghiniActionPerformed

    private void AumentarAccesoriosLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarAccesoriosLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eAccesorios= EmpleadosLamborghini.eAccesorios + 1;
            InterfazMain.eAccesoriosLamborghini.setText(String.valueOf(EmpleadosLamborghini.eAccesorios));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarAccesoriosLamborghiniActionPerformed

    private void AumentarRuedasLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarRuedasLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eRuedas= EmpleadosLamborghini.eRuedas + 1;
            InterfazMain.eRuedasLamborghini.setText(String.valueOf(EmpleadosLamborghini.eRuedas));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarRuedasLamborghiniActionPerformed

    private void DisminuirEnsambladorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirEnsambladorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eEnsamblador>1){
            EmpleadosLamborghini.eEnsamblador= EmpleadosLamborghini.eEnsamblador -1;
            InterfazMain.eEnsambladorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eEnsamblador));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirEnsambladorLamborghiniActionPerformed

    private void DisminuirRuedasLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirRuedasLamborghiniActionPerformed
        if(EmpleadosLamborghini.eRuedas>1){
            EmpleadosLamborghini.eRuedas= EmpleadosLamborghini.eRuedas -1;
            InterfazMain.eRuedasLamborghini.setText(String.valueOf(EmpleadosLamborghini.eRuedas));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirRuedasLamborghiniActionPerformed

    private void DisminuirMotorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirMotorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eMotor>1){
            EmpleadosLamborghini.eMotor= EmpleadosLamborghini.eMotor -1;
            InterfazMain.eMotorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eMotor));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirMotorLamborghiniActionPerformed

    private void DisminuirAccesoriosLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirAccesoriosLamborghiniActionPerformed
        if(EmpleadosLamborghini.eAccesorios>1){
            EmpleadosLamborghini.eAccesorios= EmpleadosLamborghini.eAccesorios -1;
            InterfazMain.eAccesoriosLamborghini.setText(String.valueOf(EmpleadosLamborghini.eAccesorios));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirAccesoriosLamborghiniActionPerformed

    private void DisminuirCarroceriaLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirCarroceriaLamborghiniActionPerformed
        if(EmpleadosLamborghini.eCarroceria>1){
            EmpleadosLamborghini.eCarroceria= EmpleadosLamborghini.eCarroceria -1;
            InterfazMain.eCarroceriaLamborghini.setText(String.valueOf(EmpleadosLamborghini.eCarroceria));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirCarroceriaLamborghiniActionPerformed

    private void AumentarCarroceriaLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarCarroceriaLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eCarroceria= EmpleadosLamborghini.eCarroceria + 1;
            InterfazMain.eCarroceriaLamborghini.setText(String.valueOf(EmpleadosLamborghini.eCarroceria));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarCarroceriaLamborghiniActionPerformed

    private void DisminuirChasisLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirChasisLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis>1){
            EmpleadosLamborghini.eChasis= EmpleadosLamborghini.eChasis -1;
            InterfazMain.eChasisLamborghini.setText(String.valueOf(EmpleadosLamborghini.eChasis));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirChasisLamborghiniActionPerformed

    private void AumentarChasisLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarChasisLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eChasis= EmpleadosLamborghini.eChasis + 1;
            InterfazMain.eChasisLamborghini.setText(String.valueOf(EmpleadosLamborghini.eChasis));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarChasisLamborghiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AumentarAccesoriosLamborghini;
    private java.awt.Button AumentarAccesoriosMaserati;
    private java.awt.Button AumentarCarroceriaLamborghini;
    private java.awt.Button AumentarCarroceriaMaserati;
    private java.awt.Button AumentarChasisLamborghini;
    private java.awt.Button AumentarChasisMaserati;
    private java.awt.Button AumentarEnsambladorLamborghini;
    private java.awt.Button AumentarEnsambladorMaserati;
    private java.awt.Button AumentarMotorLamborghini;
    private java.awt.Button AumentarMotorMaserati;
    private java.awt.Button AumentarRuedasLamborghini;
    private java.awt.Button AumentarRuedasMaserati;
    public static volatile javax.swing.JLabel CantidadAccesoriosLamborghini;
    public static volatile javax.swing.JLabel CantidadAccesoriosMaserati;
    public static volatile javax.swing.JLabel CantidadCarroceriaLamborghini;
    public static volatile javax.swing.JLabel CantidadCarroceriaMaserati;
    public static volatile javax.swing.JLabel CantidadCarrosLamborghini;
    public static volatile javax.swing.JLabel CantidadCarrosMaserati;
    public static volatile javax.swing.JLabel CantidadChasisLamborghini;
    public static volatile javax.swing.JLabel CantidadChasisMaserati;
    public static volatile javax.swing.JLabel CantidadMotorLamborghini;
    public static volatile javax.swing.JLabel CantidadMotorMaserati;
    public static volatile javax.swing.JLabel CantidadRuedasLamborghini;
    public static volatile javax.swing.JLabel CantidadRuedasMaserati;
    private java.awt.Button DisminuirAccesoriosLamborghini;
    private java.awt.Button DisminuirAccesoriosMaserati;
    private java.awt.Button DisminuirCarroceriaLamborghini;
    private java.awt.Button DisminuirCarroceriaMaserati;
    private java.awt.Button DisminuirChasisLamborghini;
    private java.awt.Button DisminuirChasisMaserati;
    private java.awt.Button DisminuirEnsambladorLamborghini;
    private java.awt.Button DisminuirEnsambladorMaserati;
    private java.awt.Button DisminuirMotorLamborghini;
    private java.awt.Button DisminuirMotorMaserati;
    private java.awt.Button DisminuirRuedasLamborghini;
    private java.awt.Button DisminuirRuedasMaserati;
    public static volatile javax.swing.JLabel EntregaLamborghini;
    public static volatile javax.swing.JLabel EntregaMaserati;
    public static volatile javax.swing.JLabel GananciasLamborghini;
    public static volatile javax.swing.JLabel GananciasMaserati;
    public static volatile javax.swing.JLabel SalariosLamborghini;
    public static volatile javax.swing.JLabel SalariosMaserati;
    public static volatile javax.swing.JLabel eAccesoriosLamborghini;
    public static volatile javax.swing.JLabel eAccesoriosMaserati;
    public static volatile javax.swing.JLabel eCarroceriaLamborghini;
    public static volatile javax.swing.JLabel eCarroceriaMaserati;
    public static volatile javax.swing.JLabel eChasisLamborghini;
    public static volatile javax.swing.JLabel eChasisMaserati;
    public static volatile javax.swing.JLabel eEnsambladorLamborghini;
    public static volatile javax.swing.JLabel eEnsambladorMaserati;
    public static volatile javax.swing.JLabel eMotorLamborghini;
    public static volatile javax.swing.JLabel eMotorMaserati;
    public static volatile javax.swing.JLabel eRuedasLamborghini;
    public static volatile javax.swing.JLabel eRuedasMaserati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
