/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import javax.swing.JOptionPane;
import automotriz.EmpleadosLamborghini;
import automotriz.EmpleadosMaserati;

/**
 *
 * @author Valeria
 */
public class InterfazMain extends javax.swing.JFrame {

    /**
     * Creates new form Pestañas
     */
    public InterfazMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CantidadCarrosLamborghini = new javax.swing.JLabel();
        CantidadCarroceriaLamborghini = new javax.swing.JLabel();
        CantidadRuedasLamborghini = new javax.swing.JLabel();
        CantidadMotorLamborghini = new javax.swing.JLabel();
        CantidadAccesoriosLamborghini = new javax.swing.JLabel();
        CantidadChasisLamborghini = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eCarroceriaLamborghini = new javax.swing.JLabel();
        eMotorLamborghini = new javax.swing.JLabel();
        eRuedasLamborghini = new javax.swing.JLabel();
        eEnsambladorLamborghini = new javax.swing.JLabel();
        eChasisLamborghini = new javax.swing.JLabel();
        eAccesoriosLamborghini = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AumentarChasisLamborghini = new java.awt.Button();
        DisminuirChasisLamborghini = new java.awt.Button();
        AumentarCarroceriaLamborghini = new java.awt.Button();
        DisminuirCarroceriaLamborghini = new java.awt.Button();
        DisminuirAccesoriosLamborghini = new java.awt.Button();
        DisminuirMotorLamborghini = new java.awt.Button();
        DisminuirRuedasLamborghini = new java.awt.Button();
        DisminuirEnsambladorLamborghini = new java.awt.Button();
        AumentarRuedasLamborghini = new java.awt.Button();
        AumentarAccesoriosLamborghini = new java.awt.Button();
        AumentarEnsambladorLamborghini = new java.awt.Button();
        AumentarMotorLamborghini = new java.awt.Button();
        estadoDirLamborghini = new javax.swing.JLabel();
        estadoLaborguini1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MaxAlmacenChasisLamborghini = new javax.swing.JLabel();
        MaxAlmacenCarroceriaLamborghini = new javax.swing.JLabel();
        MaxAlmacenMotorLamborghini = new javax.swing.JLabel();
        MaxAlmacenRuedasLamborghini = new javax.swing.JLabel();
        MaxAlmacenAccesoriosLamborghini = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        EstandarLamborghini = new javax.swing.JLabel();
        GananciasLamborghini = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        estadoLaborguini3 = new javax.swing.JLabel();
        EntregaLamborghini = new javax.swing.JLabel();
        SalarioPerdidoLamborghini = new javax.swing.JLabel();
        estadoLaborguini5 = new javax.swing.JLabel();
        estadoGerLamborghini = new javax.swing.JLabel();
        SalariosLamborghini = new javax.swing.JLabel();
        estadoLaborguini4 = new javax.swing.JLabel();
        FaltasGerenteLamborghini1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AccsLamborghini = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        CantidadCarrosMaserati = new javax.swing.JLabel();
        CantidadCarroceriaMaserati = new javax.swing.JLabel();
        CantidadRuedasMaserati = new javax.swing.JLabel();
        CantidadMotorMaserati = new javax.swing.JLabel();
        CantidadAccesoriosMaserati = new javax.swing.JLabel();
        CantidadChasisMaserati = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        eCarroceriaMaserati = new javax.swing.JLabel();
        eMotorMaserati = new javax.swing.JLabel();
        eRuedasMaserati = new javax.swing.JLabel();
        eEnsambladorMaserati = new javax.swing.JLabel();
        eChasisMaserati = new javax.swing.JLabel();
        eAccesoriosMaserati = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        AumentarChasisMaserati = new java.awt.Button();
        DisminuirChasisMaserati = new java.awt.Button();
        AumentarCarroceriaMaserati = new java.awt.Button();
        DisminuirCarroceriaMaserati = new java.awt.Button();
        DisminuirAccesoriosMaserati = new java.awt.Button();
        DisminuirMotorMaserati = new java.awt.Button();
        DisminuirRuedasMaserati = new java.awt.Button();
        DisminuirEnsambladorMaserati = new java.awt.Button();
        AumentarRuedasMaserati = new java.awt.Button();
        AumentarAccesoriosMaserati = new java.awt.Button();
        AumentarEnsambladorMaserati = new java.awt.Button();
        AumentarMotorMaserati = new java.awt.Button();
        estadoDirMaserati = new javax.swing.JLabel();
        estadoLaborguini2 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        MaxAlmacenChasisMaserati = new javax.swing.JLabel();
        MaxAlmacenCarroceriaMaserati = new javax.swing.JLabel();
        MaxAlmacenMotorMaserati = new javax.swing.JLabel();
        MaxAlmacenRuedasMaserati = new javax.swing.JLabel();
        MaxAlmacenAccesoriosMaserati = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        AccsMaserati = new javax.swing.JLabel();
        GananciasMaserati = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        estadoLaborguini7 = new javax.swing.JLabel();
        EntregaMaserati = new javax.swing.JLabel();
        SalarioPerdidoMaserati = new javax.swing.JLabel();
        estadoLaborguini8 = new javax.swing.JLabel();
        estadoGerMaserati = new javax.swing.JLabel();
        SalariosMaserati = new javax.swing.JLabel();
        estadoLaborguini10 = new javax.swing.JLabel();
        FaltasGerenteMaserati = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        AccsMaserati1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel26.setText("Leer archivo txt");
        jTabbedPane5.addTab("tab1", jLabel26);

        jTabbedPane2.addTab("Lector de Archivos", jTabbedPane5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Chasis");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel2.setText("Carroceria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 180, -1, -1));

        jLabel3.setText("Motor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel4.setText("Ruedas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel5.setText("Accesorios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        CantidadCarrosLamborghini.setText("0");
        jPanel1.add(CantidadCarrosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 40, 35));

        CantidadCarroceriaLamborghini.setText("0");
        jPanel1.add(CantidadCarroceriaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 43, 35));

        CantidadRuedasLamborghini.setText("0");
        jPanel1.add(CantidadRuedasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 43, 35));

        CantidadMotorLamborghini.setText("0");
        jPanel1.add(CantidadMotorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 43, 35));

        CantidadAccesoriosLamborghini.setText("0");
        jPanel1.add(CantidadAccesoriosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 43, 35));

        CantidadChasisLamborghini.setText("0");
        jPanel1.add(CantidadChasisLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 43, 35));

        jLabel6.setText("Salarios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel7.setText("Carros Estandar ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel8.setText("Ganancias");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, 20));

        jLabel9.setText("para la entrega");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Lamborguini");
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 143, 67));

        jLabel11.setText("asignados");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 20));

        eCarroceriaLamborghini.setText("1");
        jPanel1.add(eCarroceriaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 43, 35));

        eMotorLamborghini.setText("1");
        jPanel1.add(eMotorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 43, 35));

        eRuedasLamborghini.setText("1");
        jPanel1.add(eRuedasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 43, 35));

        eEnsambladorLamborghini.setText("1");
        jPanel1.add(eEnsambladorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 43, 35));

        eChasisLamborghini.setText("1");
        jPanel1.add(eChasisLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 43, 35));

        eAccesoriosLamborghini.setText("1");
        jPanel1.add(eAccesoriosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 43, 35));

        jLabel13.setText("Ensamblador");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        AumentarChasisLamborghini.setActionCommand("Contratar");
        AumentarChasisLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarChasisLamborghini.setLabel("A");
        AumentarChasisLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarChasisLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarChasisLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 33, -1));

        DisminuirChasisLamborghini.setActionCommand("Contratar");
        DisminuirChasisLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirChasisLamborghini.setLabel("D");
        DisminuirChasisLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirChasisLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirChasisLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 33, -1));

        AumentarCarroceriaLamborghini.setActionCommand("Contratar");
        AumentarCarroceriaLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarCarroceriaLamborghini.setLabel("A");
        AumentarCarroceriaLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarCarroceriaLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarCarroceriaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 34, -1));

        DisminuirCarroceriaLamborghini.setActionCommand("Contratar");
        DisminuirCarroceriaLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirCarroceriaLamborghini.setLabel("D");
        DisminuirCarroceriaLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirCarroceriaLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirCarroceriaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 33, -1));

        DisminuirAccesoriosLamborghini.setActionCommand("Contratar");
        DisminuirAccesoriosLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirAccesoriosLamborghini.setLabel("D");
        DisminuirAccesoriosLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirAccesoriosLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirAccesoriosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 33, -1));

        DisminuirMotorLamborghini.setActionCommand("Contratar");
        DisminuirMotorLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirMotorLamborghini.setLabel("D");
        DisminuirMotorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirMotorLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirMotorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 33, -1));

        DisminuirRuedasLamborghini.setActionCommand("Contratar");
        DisminuirRuedasLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirRuedasLamborghini.setLabel("D");
        DisminuirRuedasLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirRuedasLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirRuedasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 33, -1));

        DisminuirEnsambladorLamborghini.setActionCommand("Contratar");
        DisminuirEnsambladorLamborghini.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirEnsambladorLamborghini.setLabel("D");
        DisminuirEnsambladorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirEnsambladorLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(DisminuirEnsambladorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 33, -1));

        AumentarRuedasLamborghini.setActionCommand("Contratar");
        AumentarRuedasLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarRuedasLamborghini.setLabel("A");
        AumentarRuedasLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarRuedasLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarRuedasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 34, -1));

        AumentarAccesoriosLamborghini.setActionCommand("Contratar");
        AumentarAccesoriosLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarAccesoriosLamborghini.setLabel("A");
        AumentarAccesoriosLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarAccesoriosLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarAccesoriosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 34, -1));

        AumentarEnsambladorLamborghini.setActionCommand("Contratar");
        AumentarEnsambladorLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarEnsambladorLamborghini.setLabel("A");
        AumentarEnsambladorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarEnsambladorLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarEnsambladorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 34, -1));

        AumentarMotorLamborghini.setActionCommand("Contratar");
        AumentarMotorLamborghini.setBackground(new java.awt.Color(0, 204, 0));
        AumentarMotorLamborghini.setLabel("A");
        AumentarMotorLamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarMotorLamborghiniActionPerformed(evt);
            }
        });
        jPanel1.add(AumentarMotorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 34, -1));

        estadoDirLamborghini.setText("Activo");
        jPanel1.add(estadoDirLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        estadoLaborguini1.setText("Labor del Director");
        jPanel1.add(estadoLaborguini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel27.setText("Trabajos");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel28.setText("N° de piezas");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel29.setText("Espacio Max ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 20));

        MaxAlmacenChasisLamborghini.setText("25");
        jPanel1.add(MaxAlmacenChasisLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 43, 35));

        MaxAlmacenCarroceriaLamborghini.setText("20");
        jPanel1.add(MaxAlmacenCarroceriaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 43, 35));

        MaxAlmacenMotorLamborghini.setText("55");
        jPanel1.add(MaxAlmacenMotorLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 43, 35));

        MaxAlmacenRuedasLamborghini.setText("35");
        jPanel1.add(MaxAlmacenRuedasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 43, 35));

        MaxAlmacenAccesoriosLamborghini.setText("10");
        jPanel1.add(MaxAlmacenAccesoriosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 43, 35));

        jLabel30.setText("de Almacen");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, 80, 20));

        jLabel31.setText("disponibles");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, 20));

        jLabel32.setText("Carros ensamblados");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        EstandarLamborghini.setText("0");
        jPanel1.add(EstandarLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 43, 35));

        GananciasLamborghini.setText("0");
        jPanel1.add(GananciasLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 43, 35));

        jLabel34.setText("Dias faltantes");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        estadoLaborguini3.setText("Salario Perdido");
        jPanel1.add(estadoLaborguini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        EntregaLamborghini.setText("0");
        jPanel1.add(EntregaLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 43, 35));

        SalarioPerdidoLamborghini.setText("0");
        jPanel1.add(SalarioPerdidoLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 43, 35));

        estadoLaborguini5.setText("Labor del Gerente");
        jPanel1.add(estadoLaborguini5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        estadoGerLamborghini.setText("Activo");
        jPanel1.add(estadoGerLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        SalariosLamborghini.setText("0");
        jPanel1.add(SalariosLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 43, 35));

        estadoLaborguini4.setText("Faltas cometidas");
        jPanel1.add(estadoLaborguini4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        FaltasGerenteLamborghini1.setText("0");
        jPanel1.add(FaltasGerenteLamborghini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 43, 35));

        jLabel12.setText("Carros con accesorios ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        AccsLamborghini.setText("0");
        jPanel1.add(AccsLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 43, 35));

        jTabbedPane2.addTab("Lamborghini", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("Chasis");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel36.setText("Carroceria");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel37.setText("Motor");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel38.setText("Ruedas");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel39.setText("Accesorios");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        CantidadCarrosMaserati.setText("0");
        jPanel2.add(CantidadCarrosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 40, 35));

        CantidadCarroceriaMaserati.setText("0");
        jPanel2.add(CantidadCarroceriaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 43, 35));

        CantidadRuedasMaserati.setText("0");
        jPanel2.add(CantidadRuedasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 43, 35));

        CantidadMotorMaserati.setText("0");
        jPanel2.add(CantidadMotorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 43, 35));

        CantidadAccesoriosMaserati.setText("0");
        jPanel2.add(CantidadAccesoriosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 43, 35));

        CantidadChasisMaserati.setText("0");
        jPanel2.add(CantidadChasisMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 43, 35));

        jLabel40.setText("Salarios");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        jLabel41.setText("Carros Estandar ");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel42.setText("Ganancias");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, 20));

        jLabel43.setText("para la entrega");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, 10));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel44.setText("Maserati");
        jLabel44.setMaximumSize(new java.awt.Dimension(80, 16));
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 143, 67));

        jLabel45.setText("asignados");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 20));

        eCarroceriaMaserati.setText("1");
        jPanel2.add(eCarroceriaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 43, 35));

        eMotorMaserati.setText("1");
        jPanel2.add(eMotorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 43, 35));

        eRuedasMaserati.setText("1");
        jPanel2.add(eRuedasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 43, 35));

        eEnsambladorMaserati.setText("1");
        jPanel2.add(eEnsambladorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 43, 35));

        eChasisMaserati.setText("1");
        jPanel2.add(eChasisMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 43, 35));

        eAccesoriosMaserati.setText("1");
        jPanel2.add(eAccesoriosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 43, 35));

        jLabel46.setText("Ensamblador");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        AumentarChasisMaserati.setActionCommand("Contratar");
        AumentarChasisMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarChasisMaserati.setLabel("A");
        AumentarChasisMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarChasisMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarChasisMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 33, -1));

        DisminuirChasisMaserati.setActionCommand("Contratar");
        DisminuirChasisMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirChasisMaserati.setLabel("D");
        DisminuirChasisMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirChasisMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirChasisMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 33, -1));

        AumentarCarroceriaMaserati.setActionCommand("Contratar");
        AumentarCarroceriaMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarCarroceriaMaserati.setLabel("A");
        AumentarCarroceriaMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarCarroceriaMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarCarroceriaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 34, -1));

        DisminuirCarroceriaMaserati.setActionCommand("Contratar");
        DisminuirCarroceriaMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirCarroceriaMaserati.setLabel("D");
        DisminuirCarroceriaMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirCarroceriaMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirCarroceriaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 33, -1));

        DisminuirAccesoriosMaserati.setActionCommand("Contratar");
        DisminuirAccesoriosMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirAccesoriosMaserati.setLabel("D");
        DisminuirAccesoriosMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirAccesoriosMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirAccesoriosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 33, -1));

        DisminuirMotorMaserati.setActionCommand("Contratar");
        DisminuirMotorMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirMotorMaserati.setLabel("D");
        DisminuirMotorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirMotorMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirMotorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 33, -1));

        DisminuirRuedasMaserati.setActionCommand("Contratar");
        DisminuirRuedasMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirRuedasMaserati.setLabel("D");
        DisminuirRuedasMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirRuedasMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirRuedasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 33, -1));

        DisminuirEnsambladorMaserati.setActionCommand("Contratar");
        DisminuirEnsambladorMaserati.setBackground(new java.awt.Color(255, 0, 0));
        DisminuirEnsambladorMaserati.setLabel("D");
        DisminuirEnsambladorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirEnsambladorMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(DisminuirEnsambladorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 33, -1));

        AumentarRuedasMaserati.setActionCommand("Contratar");
        AumentarRuedasMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarRuedasMaserati.setLabel("A");
        AumentarRuedasMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarRuedasMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarRuedasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 34, -1));

        AumentarAccesoriosMaserati.setActionCommand("Contratar");
        AumentarAccesoriosMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarAccesoriosMaserati.setLabel("A");
        AumentarAccesoriosMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarAccesoriosMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarAccesoriosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 34, -1));

        AumentarEnsambladorMaserati.setActionCommand("Contratar");
        AumentarEnsambladorMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarEnsambladorMaserati.setLabel("A");
        AumentarEnsambladorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarEnsambladorMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarEnsambladorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 34, -1));

        AumentarMotorMaserati.setActionCommand("Contratar");
        AumentarMotorMaserati.setBackground(new java.awt.Color(0, 204, 0));
        AumentarMotorMaserati.setLabel("A");
        AumentarMotorMaserati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarMotorMaseratiActionPerformed(evt);
            }
        });
        jPanel2.add(AumentarMotorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 34, -1));

        estadoDirMaserati.setText("Activo");
        jPanel2.add(estadoDirMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        estadoLaborguini2.setText("Labor del Director");
        jPanel2.add(estadoLaborguini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel47.setText("Trabajos");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel48.setText("N° de piezas");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel49.setText("Espacio Max ");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 20));

        MaxAlmacenChasisMaserati.setText("25");
        jPanel2.add(MaxAlmacenChasisMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 43, 35));

        MaxAlmacenCarroceriaMaserati.setText("20");
        jPanel2.add(MaxAlmacenCarroceriaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 43, 35));

        MaxAlmacenMotorMaserati.setText("55");
        jPanel2.add(MaxAlmacenMotorMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 43, 35));

        MaxAlmacenRuedasMaserati.setText("35");
        jPanel2.add(MaxAlmacenRuedasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 43, 35));

        MaxAlmacenAccesoriosMaserati.setText("10");
        jPanel2.add(MaxAlmacenAccesoriosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 43, 35));

        jLabel50.setText("de Almacen");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 20));

        jLabel51.setText("disponibles");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 20));

        jLabel52.setText("Carros ensamblados");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        AccsMaserati.setText("0");
        jPanel2.add(AccsMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 43, 35));

        GananciasMaserati.setText("0");
        jPanel2.add(GananciasMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 43, 35));

        jLabel54.setText("Dias faltantes");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        estadoLaborguini7.setText("Salario Perdido");
        jPanel2.add(estadoLaborguini7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        EntregaMaserati.setText("0");
        jPanel2.add(EntregaMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 43, 35));

        SalarioPerdidoMaserati.setText("0");
        jPanel2.add(SalarioPerdidoMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 43, 35));

        estadoLaborguini8.setText("Labor del Gerente");
        jPanel2.add(estadoLaborguini8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        estadoGerMaserati.setText("Activo");
        jPanel2.add(estadoGerMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        SalariosMaserati.setText("0");
        jPanel2.add(SalariosMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 43, 35));

        estadoLaborguini10.setText("Faltas cometidas");
        jPanel2.add(estadoLaborguini10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        FaltasGerenteMaserati.setText("0");
        jPanel2.add(FaltasGerenteMaserati, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 43, 35));

        jLabel53.setText("Carros con accesorios ");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        AccsMaserati1.setText("0");
        jPanel2.add(AccsMaserati1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 43, 35));

        jTabbedPane2.addTab("Maserati", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AumentarMotorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarMotorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eMotor= EmpleadosLamborghini.eMotor + 1;
            InterfazMain.eMotorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eMotor));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarMotorLamborghiniActionPerformed

    private void AumentarEnsambladorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarEnsambladorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eEnsamblador= EmpleadosLamborghini.eEnsamblador + 1;
            InterfazMain.eEnsambladorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eEnsamblador));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarEnsambladorLamborghiniActionPerformed

    private void AumentarAccesoriosLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarAccesoriosLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eAccesorios= EmpleadosLamborghini.eAccesorios + 1;
            InterfazMain.eAccesoriosLamborghini.setText(String.valueOf(EmpleadosLamborghini.eAccesorios));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarAccesoriosLamborghiniActionPerformed

    private void AumentarRuedasLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarRuedasLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eRuedas= EmpleadosLamborghini.eRuedas + 1;
            InterfazMain.eRuedasLamborghini.setText(String.valueOf(EmpleadosLamborghini.eRuedas));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarRuedasLamborghiniActionPerformed

    private void DisminuirEnsambladorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirEnsambladorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eEnsamblador>1){
            EmpleadosLamborghini.eEnsamblador= EmpleadosLamborghini.eEnsamblador -1;
            InterfazMain.eEnsambladorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eEnsamblador));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirEnsambladorLamborghiniActionPerformed

    private void DisminuirRuedasLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirRuedasLamborghiniActionPerformed
        if(EmpleadosLamborghini.eRuedas>1){
            EmpleadosLamborghini.eRuedas= EmpleadosLamborghini.eRuedas -1;
            InterfazMain.eRuedasLamborghini.setText(String.valueOf(EmpleadosLamborghini.eRuedas));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirRuedasLamborghiniActionPerformed

    private void DisminuirMotorLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirMotorLamborghiniActionPerformed
        if(EmpleadosLamborghini.eMotor>1){
            EmpleadosLamborghini.eMotor= EmpleadosLamborghini.eMotor -1;
            InterfazMain.eMotorLamborghini.setText(String.valueOf(EmpleadosLamborghini.eMotor));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirMotorLamborghiniActionPerformed

    private void DisminuirAccesoriosLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirAccesoriosLamborghiniActionPerformed
        if(EmpleadosLamborghini.eAccesorios>1){
            EmpleadosLamborghini.eAccesorios= EmpleadosLamborghini.eAccesorios -1;
            InterfazMain.eAccesoriosLamborghini.setText(String.valueOf(EmpleadosLamborghini.eAccesorios));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirAccesoriosLamborghiniActionPerformed

    private void DisminuirCarroceriaLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirCarroceriaLamborghiniActionPerformed
        if(EmpleadosLamborghini.eCarroceria>1){
            EmpleadosLamborghini.eCarroceria= EmpleadosLamborghini.eCarroceria -1;
            InterfazMain.eCarroceriaLamborghini.setText(String.valueOf(EmpleadosLamborghini.eCarroceria));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirCarroceriaLamborghiniActionPerformed

    private void AumentarCarroceriaLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarCarroceriaLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eCarroceria= EmpleadosLamborghini.eCarroceria + 1;
            InterfazMain.eCarroceriaLamborghini.setText(String.valueOf(EmpleadosLamborghini.eCarroceria));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarCarroceriaLamborghiniActionPerformed

    private void DisminuirChasisLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirChasisLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis>1){
            EmpleadosLamborghini.eChasis= EmpleadosLamborghini.eChasis -1;
            InterfazMain.eChasisLamborghini.setText(String.valueOf(EmpleadosLamborghini.eChasis));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirChasisLamborghiniActionPerformed

    private void AumentarChasisLamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarChasisLamborghiniActionPerformed
        if(EmpleadosLamborghini.eChasis+EmpleadosLamborghini.eCarroceria+EmpleadosLamborghini.eMotor+
            EmpleadosLamborghini.eRuedas+EmpleadosLamborghini.eAccesorios+EmpleadosLamborghini.eEnsamblador < EmpleadosLamborghini.Empleados){
            EmpleadosLamborghini.eChasis= EmpleadosLamborghini.eChasis + 1;
            InterfazMain.eChasisLamborghini.setText(String.valueOf(EmpleadosLamborghini.eChasis));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 16 empleados");
        }
    }//GEN-LAST:event_AumentarChasisLamborghiniActionPerformed

    private void AumentarChasisMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarChasisMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eChasisMase= EmpleadosMaserati.eChasisMase + 1;
            InterfazMain.eChasisMaserati.setText(String.valueOf(EmpleadosMaserati.eChasisMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarChasisMaseratiActionPerformed

    private void DisminuirChasisMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirChasisMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase>1){
            EmpleadosMaserati.eChasisMase= EmpleadosMaserati.eChasisMase -1;
            InterfazMain.eChasisMaserati.setText(String.valueOf(EmpleadosMaserati.eChasisMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirChasisMaseratiActionPerformed

    private void AumentarCarroceriaMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarCarroceriaMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eCarroceriaMase= EmpleadosMaserati.eCarroceriaMase + 1;
            InterfazMain.eCarroceriaMaserati.setText(String.valueOf(EmpleadosMaserati.eCarroceriaMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarCarroceriaMaseratiActionPerformed

    private void DisminuirCarroceriaMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirCarroceriaMaseratiActionPerformed
        if(EmpleadosMaserati.eCarroceriaMase>1){
            EmpleadosMaserati.eCarroceriaMase= EmpleadosMaserati.eCarroceriaMase -1;
            InterfazMain.eCarroceriaMaserati.setText(String.valueOf(EmpleadosMaserati.eCarroceriaMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirCarroceriaMaseratiActionPerformed

    private void DisminuirAccesoriosMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirAccesoriosMaseratiActionPerformed
        if(EmpleadosMaserati.eAccesoriosMase>1){
            EmpleadosMaserati.eAccesoriosMase= EmpleadosMaserati.eAccesoriosMase -1;
            InterfazMain.eAccesoriosMaserati.setText(String.valueOf(EmpleadosMaserati.eAccesoriosMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirAccesoriosMaseratiActionPerformed

    private void DisminuirMotorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirMotorMaseratiActionPerformed
        if(EmpleadosMaserati.eMotorMase>1){
            EmpleadosMaserati.eMotorMase= EmpleadosMaserati.eMotorMase -1;
            InterfazMain.eMotorMaserati.setText(String.valueOf(EmpleadosMaserati.eMotorMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirMotorMaseratiActionPerformed

    private void DisminuirRuedasMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirRuedasMaseratiActionPerformed
        if(EmpleadosMaserati.eRuedasMase>1){
            EmpleadosMaserati.eRuedasMase= EmpleadosMaserati.eRuedasMase -1;
            InterfazMain.eRuedasMaserati.setText(String.valueOf(EmpleadosMaserati.eRuedasMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirRuedasMaseratiActionPerformed

    private void DisminuirEnsambladorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirEnsambladorMaseratiActionPerformed
        if(EmpleadosMaserati.eEnsambladorMase>1){
            EmpleadosMaserati.eEnsambladorMase= EmpleadosMaserati.eEnsambladorMase -1;
            InterfazMain.eEnsambladorMaserati.setText(String.valueOf(EmpleadosMaserati.eEnsambladorMase));

        }else{
            JOptionPane.showMessageDialog(null, "No se puede quedar un sector sin empleados");
        }
    }//GEN-LAST:event_DisminuirEnsambladorMaseratiActionPerformed

    private void AumentarRuedasMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarRuedasMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eRuedasMase= EmpleadosMaserati.eRuedasMase + 1;
            InterfazMain.eRuedasMaserati.setText(String.valueOf(EmpleadosMaserati.eRuedasMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarRuedasMaseratiActionPerformed

    private void AumentarAccesoriosMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarAccesoriosMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eAccesoriosMase= EmpleadosMaserati.eAccesoriosMase + 1;
            InterfazMain.eAccesoriosMaserati.setText(String.valueOf(EmpleadosMaserati.eAccesoriosMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarAccesoriosMaseratiActionPerformed

    private void AumentarEnsambladorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarEnsambladorMaseratiActionPerformed
       if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eEnsambladorMase= EmpleadosMaserati.eEnsambladorMase + 1;
            InterfazMain.eEnsambladorMaserati.setText(String.valueOf(EmpleadosMaserati.eEnsambladorMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarEnsambladorMaseratiActionPerformed

    private void AumentarMotorMaseratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarMotorMaseratiActionPerformed
        if(EmpleadosMaserati.eChasisMase+EmpleadosMaserati.eCarroceriaMase+EmpleadosMaserati.eMotorMase+
            EmpleadosMaserati.eRuedasMase+EmpleadosMaserati.eAccesoriosMase+EmpleadosMaserati.eEnsambladorMase < EmpleadosMaserati.EmpleadosMase){
            EmpleadosMaserati.eMotorMase= EmpleadosMaserati.eMotorMase + 1;
            InterfazMain.eMotorMaserati.setText(String.valueOf(EmpleadosMaserati.eMotorMase));
        }else{
            JOptionPane.showMessageDialog(null, "Ya estan ocupados los 13 empleados");
        }
    }//GEN-LAST:event_AumentarMotorMaseratiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static volatile javax.swing.JLabel AccsLamborghini;
    public static volatile javax.swing.JLabel AccsMaserati;
    public static volatile javax.swing.JLabel AccsMaserati1;
    private java.awt.Button AumentarAccesoriosLamborghini;
    private java.awt.Button AumentarAccesoriosMaserati;
    private java.awt.Button AumentarCarroceriaLamborghini;
    private java.awt.Button AumentarCarroceriaMaserati;
    private java.awt.Button AumentarChasisLamborghini;
    private java.awt.Button AumentarChasisMaserati;
    private java.awt.Button AumentarEnsambladorLamborghini;
    private java.awt.Button AumentarEnsambladorMaserati;
    private java.awt.Button AumentarMotorLamborghini;
    private java.awt.Button AumentarMotorMaserati;
    private java.awt.Button AumentarRuedasLamborghini;
    private java.awt.Button AumentarRuedasMaserati;
    public static volatile javax.swing.JLabel CantidadAccesoriosLamborghini;
    public static volatile javax.swing.JLabel CantidadAccesoriosMaserati;
    public static volatile javax.swing.JLabel CantidadCarroceriaLamborghini;
    public static volatile javax.swing.JLabel CantidadCarroceriaMaserati;
    public static volatile javax.swing.JLabel CantidadCarrosLamborghini;
    public static volatile javax.swing.JLabel CantidadCarrosMaserati;
    public static volatile javax.swing.JLabel CantidadChasisLamborghini;
    public static volatile javax.swing.JLabel CantidadChasisMaserati;
    public static volatile javax.swing.JLabel CantidadMotorLamborghini;
    public static volatile javax.swing.JLabel CantidadMotorMaserati;
    public static volatile javax.swing.JLabel CantidadRuedasLamborghini;
    public static volatile javax.swing.JLabel CantidadRuedasMaserati;
    private java.awt.Button DisminuirAccesoriosLamborghini;
    private java.awt.Button DisminuirAccesoriosMaserati;
    private java.awt.Button DisminuirCarroceriaLamborghini;
    private java.awt.Button DisminuirCarroceriaMaserati;
    private java.awt.Button DisminuirChasisLamborghini;
    private java.awt.Button DisminuirChasisMaserati;
    private java.awt.Button DisminuirEnsambladorLamborghini;
    private java.awt.Button DisminuirEnsambladorMaserati;
    private java.awt.Button DisminuirMotorLamborghini;
    private java.awt.Button DisminuirMotorMaserati;
    private java.awt.Button DisminuirRuedasLamborghini;
    private java.awt.Button DisminuirRuedasMaserati;
    public static volatile javax.swing.JLabel EntregaLamborghini;
    public static volatile javax.swing.JLabel EntregaMaserati;
    public static volatile javax.swing.JLabel EstandarLamborghini;
    public static volatile javax.swing.JLabel FaltasGerenteLamborghini1;
    public static volatile javax.swing.JLabel FaltasGerenteMaserati;
    public static volatile javax.swing.JLabel GananciasLamborghini;
    public static volatile javax.swing.JLabel GananciasMaserati;
    public static volatile javax.swing.JLabel MaxAlmacenAccesoriosLamborghini;
    public static volatile javax.swing.JLabel MaxAlmacenAccesoriosMaserati;
    public static volatile javax.swing.JLabel MaxAlmacenCarroceriaLamborghini;
    public static volatile javax.swing.JLabel MaxAlmacenCarroceriaMaserati;
    public static volatile javax.swing.JLabel MaxAlmacenChasisLamborghini;
    public static volatile javax.swing.JLabel MaxAlmacenChasisMaserati;
    public static volatile javax.swing.JLabel MaxAlmacenMotorLamborghini;
    public static volatile javax.swing.JLabel MaxAlmacenMotorMaserati;
    public static volatile javax.swing.JLabel MaxAlmacenRuedasLamborghini;
    public static volatile javax.swing.JLabel MaxAlmacenRuedasMaserati;
    public static volatile javax.swing.JLabel SalarioPerdidoLamborghini;
    public static volatile javax.swing.JLabel SalarioPerdidoMaserati;
    public static volatile javax.swing.JLabel SalariosLamborghini;
    public static volatile javax.swing.JLabel SalariosMaserati;
    public static volatile javax.swing.JLabel eAccesoriosLamborghini;
    public static volatile javax.swing.JLabel eAccesoriosMaserati;
    public static volatile javax.swing.JLabel eCarroceriaLamborghini;
    public static volatile javax.swing.JLabel eCarroceriaMaserati;
    public static volatile javax.swing.JLabel eChasisLamborghini;
    public static volatile javax.swing.JLabel eChasisMaserati;
    public static volatile javax.swing.JLabel eEnsambladorLamborghini;
    public static volatile javax.swing.JLabel eEnsambladorMaserati;
    public static volatile javax.swing.JLabel eMotorLamborghini;
    public static volatile javax.swing.JLabel eMotorMaserati;
    public static volatile javax.swing.JLabel eRuedasLamborghini;
    public static volatile javax.swing.JLabel eRuedasMaserati;
    public static volatile javax.swing.JLabel estadoDirLamborghini;
    public static volatile javax.swing.JLabel estadoDirMaserati;
    public static volatile javax.swing.JLabel estadoGerLamborghini;
    public static volatile javax.swing.JLabel estadoGerMaserati;
    private javax.swing.JLabel estadoLaborguini1;
    private javax.swing.JLabel estadoLaborguini10;
    private javax.swing.JLabel estadoLaborguini2;
    private javax.swing.JLabel estadoLaborguini3;
    private javax.swing.JLabel estadoLaborguini4;
    private javax.swing.JLabel estadoLaborguini5;
    private javax.swing.JLabel estadoLaborguini7;
    private javax.swing.JLabel estadoLaborguini8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
